version: "3.9"
services:
  nodejs:
    image: node:20.12.1
    working_dir: /usr/src/app
    ports:
      - "${NODE_PORT}:3000"
    expose:
      - ${NODE_PORT}
    depends_on:
      - mongodb
    volumes:
      - ".:/usr/src/app"
    command: sh -c "npm run start:dev"
    restart: always


  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    expose:
      - ${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - data-mongodb:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
    data-mongodb: